### ISSUE TITLE
Bei Rezeptnamen mit einem Sonderzeichen im Titel (z.B. "()") funktioniert die Bilddarstellung nicht richtig 

### ISSUE THREAD

**Issue by Miwri** [fabianhinz/RecipeHandler-4.0#1209]
Lösungsansatz: konsistentes URL-Encoden des Titels 

![image](https://user-images.githubusercontent.com/44898638/146897443-c0c487d5-fd5b-42ac-9fca-1c5e8fc38dde.png)

**Comment by fabianhinz** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape 
;)
