### ISSUE TITLE
Ausgabenmanager

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/RecipeHandler-4.0#784]
**Eingaben:**

- Ausgebende Person (Autocomplete Textfeld (MUI). Dynamisch erweiterbare Liste im Firestore)
- Betrag
- Datum
- Kategorie (Fix im Firestore, z.B. Nahrungsmittel, Mobilität, Inventar, Sonstiges)
- Unterkategorie (Autocomplete Textfeld (MUI), dynamisch erweiterbare Liste im Firestore, z.B. Kaffee, Farbe, ...)
- Markt (Laden in dem gekauft wurde, Autocomplete Textfeld (MUI), dynamisch erweiterbare Liste im Firestore)
- Auswahl der betreffenden Personen. Abgebildet als Chips, defaultmäßig alle angehakt.

**Auswertungen:**

- Kontostand der Personen (Differenz über gesamten Zeitraum, summierte Ausgaben auf bestimmte Zeiträume)
- Trendverlauf basierend auf Zeitachse (z.B. wie haben sich die gesamten Ausgaben/ gruppiert nach bestimmten Kategorien im Zeitverlauf entwickelt)
- Gruppierungen der Gesamtausgaben nach Kategorie, Unterkategorie, Markt
- tbc ... 

**Ansichten:**

![My First Board - Frame 1](https://user-images.githubusercontent.com/44898638/110242685-74990600-7f57-11eb-8e18-7ffc43bec256.jpg)
![My First Board - Frame 3](https://user-images.githubusercontent.com/44898638/110242687-75319c80-7f57-11eb-92ce-a73e34ee8027.jpg)

**Umsetzungen:**
- Autocomplete über Cloudfunction realisieren => Collection welche mögliche Werte enthält, brauchen wir das? Oder kann man bei Neuanlage einer Kategorie einfach ein write in den Firestore machen?  
- import { mdiPiggyBank } from '@mdi/js';

**Comment by Miwri** [comment]
Ausstehende Arbeiten: 

- mobile Ansicht anpassen
- Form Validierung
- Dialoge für löschen
- Privacy Features (Annonymes login ausschalten, Rezepte per Default nicht sichtbar => Möglichkeit diese Sichtbar zu machen)
- Store auf Firestore umziehen

**Comment by Miwri** [comment]
Anonymes Login rauswerfen

Was ist versteckt? 
* Nichts Nutzerbezogenes
* Keine Kommentare
* Kein Zuletzt hinzugefügt
* Kein häufig gekocht
* Kein zuletzt bearbeitet
* Keine Ideen
* Keine Nutzer

Was darf ein Gast? 
* Rezepte sehen
* Rezeptbilder sehen
* Kategorien sehen
* Filtern
* Suchen

**Comment by Miwri** [comment]
TODOs: 
- Autocomplete für User, Geschäft, Kategorie und Beschreibung in den Firestore umziehen. => Befüllen über eine Function
- Form Validierung
- Dialoge für Löschen
- mobile Ansicht anpassen
- anonymes Login ausschalten bevor Merge

**Comment by Miwri** [comment]
spätere Featues:
- groupby "Monat"
