### ISSUE TITLE
Weiterentwicklung Ausgabenverwaltung

### ISSUE THREAD

**Issue by fabianhinz** [fabianhinz/RecipeHandler-4.0#902]
- [ ] skeletons 
- [ ] error boundaries
- [x] Hintergrund icon tauschen 
- [ ] firestore rules schärfen (siehe todo)
- [x] User Card
  - [x] Konstostand und Ausgaben labels raus und Kontostand (grün/rot) präsenter 
  - [x] Balkendiagramm (tiny) zur schnellen Übersicht über alle Ausgabenkategorien (aufsummiert)
  - [x] Bild upload / oder Avatar ganz raus
  - [x] Pie Tooltip

__

Inspiration:
![image](https://user-images.githubusercontent.com/22753474/119270158-9b341800-bbfb-11eb-8e24-5837a5068058.png)
https://dribbble.com/shots/14706714-Integration-dashboard

![image](https://user-images.githubusercontent.com/22753474/119270197-d46c8800-bbfb-11eb-9a3a-98153e1cf8f1.png)
https://dribbble.com/shots/15123056-Weekly-Summary-Email

**Comment by Miwri** [comment]
![image](https://user-images.githubusercontent.com/44898638/120100038-f35ca400-c13e-11eb-86d5-4ebf65808eb6.png)

![image](https://user-images.githubusercontent.com/44898638/120100055-fd7ea280-c13e-11eb-8339-cfbfbfd66c29.png)

**Comment by fabianhinz** [comment]
ein paar Dashboard-Design ideen:
https://demos.wrappixel.com/premium-admin-templates/react/flexy-react/dark/#/dashboards/dashboard1
https://material-ui.com/store/previews/tokyo-react-admin-dashboard/
https://material-ui.com/store/previews/minimal-dashboard/
